### ISSUE TITLE
Upgrade go-control-plane to support the new protocol

### ISSUE THREAD

**Issue by georgasa** [smallstep/step-sds#7] opened 2020-05-25 22:44 UTC
Hello,
while docker-compose is able to start and it spawns the envoy, envoy-sds, sds, ca, back/front ends containers, I'm getting constantly the following error:
...

ca_1         | time="2020-05-25T22:38:05Z" level=info certificate="MIICKzCCAdCgAwIBAgIQE+g/M1e/lN4oljJ6reWXCzAKBggqhkjOPQQDAjAkMSIwIAYDVQQDExlTbWFsbHN0ZXAgSW50ZXJtZWRpYXRlIENBMB4XDTIwMDUyNTIyMzcwNVoXDTIwMDUyNTIyMzkwNVowHjEcMBoGA1UEAxMTaGVsbG8uc21hbGxzdGVwLmNvbTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABLIgc4UmQ7KeEN0tu8tq0A3Ecy1euAdIiDgqSItASSXOedR1OuD1M2+q8G7fFxw1KxvbNoGENvo91NvULqwwTYyjgekwgeYwHwYDVR0jBBgwFoAUQzNYWbowdwotixBbGLCXiifU9w0wDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNVHQ4EFgQUFWFuZssc4Yw5qtBBeJ3SaaOMvWswHgYDVR0RBBcwFYITaGVsbG8uc21hbGxzdGVwLmNvbTBVBgwrBgEEAYKkZMYoQAEERTBDAgEBBBFzZHNAc21hbGxzdGVwLmNvbQQrb0ExeDJuVjN5Q2xhZjJrUWRQT0pfTEV6VEd3NW93NHIyQTVTV2wzTWZNZzAKBggqhkjOPQQDAgNJADBGAiEAqga5TdvAlZ/WxSSCaDZ1d7ymMjUGbbtDKEdchiRe5OoCIQDZTI/v9IzdUBTkU1JLaN/1EoG8TXnKUnw/dxBugVjNug==" duration="644.95µs" duration-ns=644950 fields.time="2020-05-25T22:38:05Z" issuer="Smallstep Intermediate CA" method=POST name=ca path=/renew protocol=HTTP/2.0 provisioner="sds@smallstep.com (oA1x2nV3yClaf2kQdPOJ_LEzTGw5ow4r2A5SWl3MfMg)" public-key="ECDSA P-256" referer= remote-address=172.19.0.5 request-id=br64hjecu46ennni73fg serial=26461226650691603572053979974223632139 size=3150 status=201 subject=hello.smallstep.com user-agent=Go-http-client/2.0 user-id= valid-from="2020-05-25T22:37:05Z" valid-to="2020-05-25T22:39:05Z"
sds_1        | time="2020-05-25T22:38:05Z" level=info msg="Certificate renewed" cluster=hello-tls grpc.duration="390.443µs" grpc.duration-ns=390443 grpc.method=StreamSecrets grpc.package=envoy.service.discovery.v2 grpc.service=SecretDiscoveryService grpc.start_time="2020-05-25T22:38:05Z" node=envoy.smallstep.com nonce=1de73470625bf32e23532c9dfb9ad0b127bb1baff058fdf09f71d2f865c29708 resourceNames="[internal.smallstep.com]" responseNonce= span.kind=server system=grpc versionInfo=
sds_1        | time="2020-05-25T22:38:05Z" level=info msg="Certificate renewed" cluster=hello-tls grpc.duration="415.592µs" grpc.duration-ns=415592 grpc.method=StreamSecrets grpc.package=envoy.service.discovery.v2 grpc.service=SecretDiscoveryService grpc.start_time="2020-05-25T22:38:05Z" node=envoy.smallstep.com nonce=ff7e52f5dd8f5acd350f96f317cd4bf70de083995875d5892642a830ffdfef1e resourceNames="[hello.smallstep.com]" responseNonce= span.kind=server system=grpc versionInfo=
envoy-sds_1  | [2020-05-25 22:38:12.367][24][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamSecrets gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
envoy-sds_1  | [2020-05-25 22:38:12.787][24][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamSecrets gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure
envoy-sds_1  | [2020-05-25 22:38:21.643][24][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:92] StreamSecrets gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection failure

Could you please advice what's the issue here? No changes from my side, except I'm using envoy-alpine:v1.14.1 as envoy image.

Additionally, how the ca communicates with sds?

Many thanks,
Apostolos

**Comment by maraino** [comment] 2020-05-26 20:09
> Additionally, how the ca communicates with sds?

The CA and step-sds communicate through TLS, and certificates are initially generated using retrieving an encrypted JWK key, decrypting it with a secret configured in `step-sds`. After that initial certificate they are renewed using an mTLS connection using the generated certificate.

Then Envoy and step-sds communicate though unix domain sockets or through mTLS, the example have both configurations.

I'll look into that error.

**Comment by maraino** [comment] 2020-05-26 20:50
@georgasa I've can reproduce the error with `v1.14.1`. 

It does not happen with `v1.10.0` that was the latest version ~ 1 year ago, when I developed step-sds. I've checked, and there are changes in the protocol since then, and as we never "oficially released" this product, we haven't updated it, so my guess this is the cause of the error.

I've tagged the envoy images with `envoyproxy/envoy-alpine:v1.10.0` so you can properly build and run the example properly (`docker-compose rm && docker-compose up --build`).

**Comment by tvh** [comment] 2022-09-16 12:12
This should be fixed by https://github.com/smallstep/step-sds/pull/12 right?

**Comment by maraino** [comment] 2022-09-16 17:12
Fixed by #12

**Closed by maraino** 2022-09-16 17:12 UTC
Labels: enhancement
